# site settings
title: Even So
subtitle: by Tristen Even
email: tristengeven@gmail.com
description: This site is intended to exhibit the progression of <br /> my studies and hobbies. Have a look around.
baseurl: "/" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address:
city: Berlin
state:
zip_code:
country: Germany
phone: "Current: +49 176 3696 2391 <br /> Alternate (currently disabled): 469-371-8598"

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 12

# social settings
500px_url:
facebook_url: https://www.facebook.com/tristengeven
github_url: https://github.com/tristengeven/
gitlab_url: 
googleplus_url:
instagram_url: https://www.instagram.com/thenamestristen/
linkedin_url: https://linkedin.com/in/tristeneven/
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
