[[redirects]]
  from = "/games/wordle"
  to = "https://evenwordle.netlify.app"

[[redirects]]
  from = "/games/hangman"
  to = "https://evenhangman.netlify.app" 

[[redirects]]
  from = "/games/brick"
  to = "https://evenbrick.netlify.app"  

[[redirects]]
  from = "/worship"
  to = "https://worship-together.netlify.app/" 